# Generated by Django 5.0.6 on 2024-09-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='quantity',
            new_name='prize_varaint',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_variant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_img',
            field=models.ImageField(default='/product_pictures/default.png', upload_to='variant_pictures'),
        ),
    ]
