# Generated by Django 5.0.6 on 2024-10-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_ordersummary_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
