# Generated by Django 5.0.6 on 2024-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_quantity_productvariant_prize_varaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='prize_varaint',
            new_name='price_variant',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size_variant',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
