# Generated by Django 5.0.6 on 2024-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shippingaddress_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='order_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
