# Generated by Django 5.0.6 on 2024-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_ordersummary_product_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='payment_method',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
