# Generated by Django 5.0.6 on 2024-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_ordersummary_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Dilivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=200),
        ),
    ]
