# Generated by Django 5.0.6 on 2024-10-06 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_ordersummary_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='product_variant_object',
        ),
        migrations.AddField(
            model_name='reviews',
            name='product_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='store.product'),
            preserve_default=False,
        ),
    ]
