# Generated by Django 5.0.6 on 2024-10-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_reviews_product_variant_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
